/*
 * This file is generated by jOOQ.
 */
package com.ezpc.mysql.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Country implements Serializable {

    private static final long serialVersionUID = 1L;

    private String uuid;
    private String name;

    public Country() {}

    public Country(Country value) {
        this.uuid = value.uuid;
        this.name = value.name;
    }

    public Country(
        String uuid,
        String name
    ) {
        this.uuid = uuid;
        this.name = name;
    }

    /**
     * Getter for <code>spring.country.uuid</code>.
     */
    public String getUuid() {
        return this.uuid;
    }

    /**
     * Setter for <code>spring.country.uuid</code>.
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * Getter for <code>spring.country.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>spring.country.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Country (");

        sb.append(uuid);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
