/*
 * This file is generated by jOOQ.
 */
package com.ezpc.mysql.tables.records;


import com.ezpc.mysql.tables.Drug;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DrugRecord extends UpdatableRecordImpl<DrugRecord> implements Record4<Integer, String, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>spring.drug.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>spring.drug.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>spring.drug.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>spring.drug.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>spring.drug.type</code>.
     */
    public void setType(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>spring.drug.type</code>.
     */
    public Integer getType() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>spring.drug.aliases</code>.
     */
    public void setAliases(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>spring.drug.aliases</code>.
     */
    public String getAliases() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, Integer, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Drug.DRUG.ID;
    }

    @Override
    public Field<String> field2() {
        return Drug.DRUG.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Drug.DRUG.TYPE;
    }

    @Override
    public Field<String> field4() {
        return Drug.DRUG.ALIASES;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getType();
    }

    @Override
    public String component4() {
        return getAliases();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getType();
    }

    @Override
    public String value4() {
        return getAliases();
    }

    @Override
    public DrugRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DrugRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public DrugRecord value3(Integer value) {
        setType(value);
        return this;
    }

    @Override
    public DrugRecord value4(String value) {
        setAliases(value);
        return this;
    }

    @Override
    public DrugRecord values(Integer value1, String value2, Integer value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DrugRecord
     */
    public DrugRecord() {
        super(Drug.DRUG);
    }

    /**
     * Create a detached, initialised DrugRecord
     */
    public DrugRecord(Integer id, String name, Integer type, String aliases) {
        super(Drug.DRUG);

        setId(id);
        setName(name);
        setType(type);
        setAliases(aliases);
        resetChangedOnNotNull();
    }
}
