/*
 * This file is generated by jOOQ.
 */
package com.ezpc.mysql.tables.records;


import com.ezpc.mysql.tables.Patient;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PatientRecord extends UpdatableRecordImpl<PatientRecord> implements Record9<Long, String, String, Byte, String, String, String, String, LocalDate> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>spring.patient.hospitalId</code>.
     */
    public void setHospitalid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>spring.patient.hospitalId</code>.
     */
    public Long getHospitalid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>spring.patient.uuid</code>.
     */
    public void setUuid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>spring.patient.uuid</code>.
     */
    public String getUuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>spring.patient.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>spring.patient.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>spring.patient.sex</code>.
     */
    public void setSex(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>spring.patient.sex</code>.
     */
    public Byte getSex() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>spring.patient.address</code>.
     */
    public void setAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>spring.patient.address</code>.
     */
    public String getAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>spring.patient.phoneNumber</code>.
     */
    public void setPhonenumber(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>spring.patient.phoneNumber</code>.
     */
    public String getPhonenumber() {
        return (String) get(5);
    }

    /**
     * Setter for <code>spring.patient.email</code>.
     */
    public void setEmail(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>spring.patient.email</code>.
     */
    public String getEmail() {
        return (String) get(6);
    }

    /**
     * Setter for <code>spring.patient.country</code>.
     */
    public void setCountry(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>spring.patient.country</code>.
     */
    public String getCountry() {
        return (String) get(7);
    }

    /**
     * Setter for <code>spring.patient.birthdate</code>.
     */
    public void setBirthdate(LocalDate value) {
        set(8, value);
    }

    /**
     * Getter for <code>spring.patient.birthdate</code>.
     */
    public LocalDate getBirthdate() {
        return (LocalDate) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, Byte, String, String, String, String, LocalDate> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, String, String, Byte, String, String, String, String, LocalDate> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Patient.PATIENT.HOSPITALID;
    }

    @Override
    public Field<String> field2() {
        return Patient.PATIENT.UUID;
    }

    @Override
    public Field<String> field3() {
        return Patient.PATIENT.NAME;
    }

    @Override
    public Field<Byte> field4() {
        return Patient.PATIENT.SEX;
    }

    @Override
    public Field<String> field5() {
        return Patient.PATIENT.ADDRESS;
    }

    @Override
    public Field<String> field6() {
        return Patient.PATIENT.PHONENUMBER;
    }

    @Override
    public Field<String> field7() {
        return Patient.PATIENT.EMAIL;
    }

    @Override
    public Field<String> field8() {
        return Patient.PATIENT.COUNTRY;
    }

    @Override
    public Field<LocalDate> field9() {
        return Patient.PATIENT.BIRTHDATE;
    }

    @Override
    public Long component1() {
        return getHospitalid();
    }

    @Override
    public String component2() {
        return getUuid();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Byte component4() {
        return getSex();
    }

    @Override
    public String component5() {
        return getAddress();
    }

    @Override
    public String component6() {
        return getPhonenumber();
    }

    @Override
    public String component7() {
        return getEmail();
    }

    @Override
    public String component8() {
        return getCountry();
    }

    @Override
    public LocalDate component9() {
        return getBirthdate();
    }

    @Override
    public Long value1() {
        return getHospitalid();
    }

    @Override
    public String value2() {
        return getUuid();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Byte value4() {
        return getSex();
    }

    @Override
    public String value5() {
        return getAddress();
    }

    @Override
    public String value6() {
        return getPhonenumber();
    }

    @Override
    public String value7() {
        return getEmail();
    }

    @Override
    public String value8() {
        return getCountry();
    }

    @Override
    public LocalDate value9() {
        return getBirthdate();
    }

    @Override
    public PatientRecord value1(Long value) {
        setHospitalid(value);
        return this;
    }

    @Override
    public PatientRecord value2(String value) {
        setUuid(value);
        return this;
    }

    @Override
    public PatientRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public PatientRecord value4(Byte value) {
        setSex(value);
        return this;
    }

    @Override
    public PatientRecord value5(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public PatientRecord value6(String value) {
        setPhonenumber(value);
        return this;
    }

    @Override
    public PatientRecord value7(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public PatientRecord value8(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public PatientRecord value9(LocalDate value) {
        setBirthdate(value);
        return this;
    }

    @Override
    public PatientRecord values(Long value1, String value2, String value3, Byte value4, String value5, String value6, String value7, String value8, LocalDate value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PatientRecord
     */
    public PatientRecord() {
        super(Patient.PATIENT);
    }

    /**
     * Create a detached, initialised PatientRecord
     */
    public PatientRecord(Long hospitalid, String uuid, String name, Byte sex, String address, String phonenumber, String email, String country, LocalDate birthdate) {
        super(Patient.PATIENT);

        setHospitalid(hospitalid);
        setUuid(uuid);
        setName(name);
        setSex(sex);
        setAddress(address);
        setPhonenumber(phonenumber);
        setEmail(email);
        setCountry(country);
        setBirthdate(birthdate);
        resetChangedOnNotNull();
    }
}
