/*
 * This file is generated by jOOQ.
 */
package com.ezpc.mysql;


import com.ezpc.mysql.tables.Country;
import com.ezpc.mysql.tables.Developer;
import com.ezpc.mysql.tables.records.CountryRecord;
import com.ezpc.mysql.tables.records.DeveloperRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * spring.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CountryRecord> KEY_COUNTRY_PRIMARY = Internal.createUniqueKey(Country.COUNTRY, DSL.name("KEY_country_PRIMARY"), new TableField[] { Country.COUNTRY.UUID }, true);
    public static final UniqueKey<DeveloperRecord> KEY_DEVELOPER_PRIMARY = Internal.createUniqueKey(Developer.DEVELOPER, DSL.name("KEY_developer_PRIMARY"), new TableField[] { Developer.DEVELOPER.UUID }, true);
}
