/*
 * This file is generated by jOOQ.
 */
package com.ezpc.mysql;


import com.ezpc.mysql.tables.Country;
import com.ezpc.mysql.tables.Developer;


/**
 * Convenience access to all tables in spring.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>spring.country</code>.
     */
    public static final Country COUNTRY = Country.COUNTRY;

    /**
     * The table <code>spring.developer</code>.
     */
    public static final Developer DEVELOPER = Developer.DEVELOPER;
}
