/*
 * This file is generated by jOOQ.
 */
package com.ezpc.mysql.tables;


import com.ezpc.mysql.Keys;
import com.ezpc.mysql.Spring;
import com.ezpc.mysql.tables.records.HospitaldoctorRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Hospitaldoctor extends TableImpl<HospitaldoctorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>spring.hospitalDoctor</code>
     */
    public static final Hospitaldoctor HOSPITALDOCTOR = new Hospitaldoctor();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HospitaldoctorRecord> getRecordType() {
        return HospitaldoctorRecord.class;
    }

    /**
     * The column <code>spring.hospitalDoctor.hospitalId</code>.
     */
    public final TableField<HospitaldoctorRecord, Long> HOSPITALID = createField(DSL.name("hospitalId"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>spring.hospitalDoctor.doctorId</code>.
     */
    public final TableField<HospitaldoctorRecord, String> DOCTORID = createField(DSL.name("doctorId"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>spring.hospitalDoctor.permissions</code>.
     */
    public final TableField<HospitaldoctorRecord, JSON> PERMISSIONS = createField(DSL.name("permissions"), SQLDataType.JSON.nullable(false), this, "");

    private Hospitaldoctor(Name alias, Table<HospitaldoctorRecord> aliased) {
        this(alias, aliased, null);
    }

    private Hospitaldoctor(Name alias, Table<HospitaldoctorRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>spring.hospitalDoctor</code> table reference
     */
    public Hospitaldoctor(String alias) {
        this(DSL.name(alias), HOSPITALDOCTOR);
    }

    /**
     * Create an aliased <code>spring.hospitalDoctor</code> table reference
     */
    public Hospitaldoctor(Name alias) {
        this(alias, HOSPITALDOCTOR);
    }

    /**
     * Create a <code>spring.hospitalDoctor</code> table reference
     */
    public Hospitaldoctor() {
        this(DSL.name("hospitalDoctor"), null);
    }

    public <O extends Record> Hospitaldoctor(Table<O> child, ForeignKey<O, HospitaldoctorRecord> key) {
        super(child, key, HOSPITALDOCTOR);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Spring.SPRING;
    }

    @Override
    public UniqueKey<HospitaldoctorRecord> getPrimaryKey() {
        return Keys.KEY_HOSPITALDOCTOR_PRIMARY;
    }

    @Override
    public Hospitaldoctor as(String alias) {
        return new Hospitaldoctor(DSL.name(alias), this);
    }

    @Override
    public Hospitaldoctor as(Name alias) {
        return new Hospitaldoctor(alias, this);
    }

    @Override
    public Hospitaldoctor as(Table<?> alias) {
        return new Hospitaldoctor(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Hospitaldoctor rename(String name) {
        return new Hospitaldoctor(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Hospitaldoctor rename(Name name) {
        return new Hospitaldoctor(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Hospitaldoctor rename(Table<?> name) {
        return new Hospitaldoctor(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, JSON> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Long, ? super String, ? super JSON, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Long, ? super String, ? super JSON, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
